### ISSUE TITLE
Git-sync crashes when I try syncing with my Forgejo instance

### ISSUE THREAD

**Issue by jasonbraganza** [AkashRajpurohit/git-sync#42]
### Describe the Bug

I’m new to this, so if there’s anything you folks need clarification on or additional data about, please let me know.

The status quo is as follows …
1. I have configured Forgejo to be a pull mirror for a few repos from my git hub account
2. These are private repos on my forgejo account
3. I have  created a token (various tokens all with varying amounts of read access. Is write access required? Right now the token in use, is a read only, admin level access token

### Steps to reproduce

run git-sync with the configured file against a forgejo instance

my config is as follows

```
# Git Sync Configuration for code.janusworx.com (Forgejo)

# Repository settings
include_forks: true # Include forked repositories
include_wiki: false # Include wiki's temporary. check in future versions
include_repos: [] # Include specific repositories
exclude_repos: [] # Exclude specific repositories
include_orgs: [] # Include repositories from specific organizations
exclude_orgs: [] # Exclude repositories from specific organizations

# Forgejo (code.janusworx.com) settings
username: my-user-name
token: some-admin-token
backup_dir: /code-bkp-folder
platform: forgejo
server:	  
  domain: code.janusworx.com
  protocol: https
```

I’ve pasted the output of few runs below.

### Relevant log output

```shell
{"level":"fatal","time":"2024-09-30T18:19:00.297+0530","message":"Error updating repo jasonbraganza/mjb-internet-weblog-mirror: exit status 128\n","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/home/runner/work/git-sync/git-sync/pkg/logger/logger.go:96\ngithub.com/AkashRajpurohit/git-sync/pkg/sync.CloneOrUpdateRepo\n\t/home/runner/work/git-sync/git-sync/pkg/sync/sync.go:39\ngithub.com/AkashRajpurohit/git-sync/pkg/forgejo.ForgejoClient.Sync.func1\n\t/home/runner/work/git-sync/git-sync/pkg/forgejo/forgejo.go:52"}

---

{"level":"fatal","time":"2024-09-30T18:18:44.737+0530","message":"Error updating repo jasonbraganza/mjb-frappe-books-mirror: exit status 128\n","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/home/runner/work/git-sync/git-sync/pkg/logger/logger.go:96\ngithub.com/AkashRajpurohit/git-sync/pkg/sync.CloneOrUpdateRepo\n\t/home/runner/work/git-sync/git-sync/pkg/sync/sync.go:39\ngithub.com/AkashRajpurohit/git-sync/pkg/forgejo.ForgejoClient.Sync.func1\n\t/home/runner/work/git-sync/git-sync/pkg/forgejo/forgejo.go:52"}

---

{"level":"fatal","time":"2024-09-30T18:20:25.716+0530","message":"Error updating repo jasonbraganza/mjb-hugo-PaperMod-mirror: exit status 128\n","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/home/runner/work/git-sync/git-sync/pkg/logger/logger.go:96\ngithub.com/AkashRajpurohit/git-sync/pkg/sync.CloneOrUpdateRepo\n\t/home/runner/work/git-sync/git-sync/pkg/sync/sync.go:39\ngithub.com/AkashRajpurohit/git-sync/pkg/forgejo.ForgejoClient.Sync.func1\n\t/home/runner/work/git-sync/git-sync/pkg/forgejo/forgejo.go:52"}

---

{"level":"fatal","time":"2024-09-30T18:23:35.341+0530","message":"Error updating repo jasonbraganza/mjb-Awesome-CV-mirror: exit status 128\n","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/home/runner/work/git-sync/git-sync/pkg/logger/logger.go:96\ngithub.com/AkashRajpurohit/git-sync/pkg/sync.CloneOrUpdateRepo\n\t/home/runner/work/git-sync/git-sync/pkg/sync/sync.go:39\ngithub.com/AkashRajpurohit/git-sync/pkg/forgejo.ForgejoClient.Sync.func1\n\t/home/runner/work/git-sync/git-sync/pkg/forgejo/forgejo.go:52"}
```

### Which version of the software are you using?

v0.10.0

### Which operating system are you using?

Linux Mint 22 Wilma (Based of Ubuntu 24.04)

### runtime

Binary
