### ISSUE TITLE
Fail if config is not valid instead of initializing a default one

### ISSUE THREAD

**Issue by 3timeslazy** [AkashRajpurohit/git-sync#85]
### Describe the feature or enhancement

Hi there,

I’m running git-sync in Docker, and I recently spent some time troubleshooting an issue with my configuration. The container would repeatedly complain that the config file was not found and would attempt to overwrite it. However, the volume path was absolutely correct (otherwise the container wouldn't have been able to rewrite the file). After some investigation, I realized that when the config file is invalid, git-sync creates a default configuration, which ultimately fails because the default config doesn't contain enough information to perform the sync.

I suggest updating the behavior so that the container fails immediately when the config is invalid, rather than creating a default config.

This issue occurs here: https://github.com/AkashRajpurohit/git-sync/blob/ceec51d3fe148bc2b14acb09932bb3d1f7f42a50/cmd/root.go#L36-L39

If helpful, I’m ready to submit a PR with a fix.

Thanks for your great project!

**Comment by AkashRajpurohit** [comment]
> when the config file is invalid, git-sync creates a default configuration

I don't think that is true, if it fails to load the config file, only then a new default config file is created, if for invalid configuration it will throw some sort of validation error.

Can you specify some more details about your scenario, what is does your config file looks like (removing sensitive info), your docker command or compose file and specifically its volume mount etc.

**Comment by 3timeslazy** [comment]
Sure,

`compose.yaml`

```yaml
services:
  git-sync:
    image: ghcr.io/akashrajpurohit/git-sync:v0.15.1
    command:
      - --config=/git-sync/config.yaml
      - --backup-dir=/backups
      # - --log-level=debug
    volumes:
      - ./config.yaml:/git-sync/config.yaml
      - ./data:/backups
    environment:
      PUID: 1000
      PGID: 100
    restart: no
```

`config.yaml` before I run the container

```yaml
backup_dir: /backups
clone_type: bare
concurrency: 5
include_forks: false
include_wiki: true
retry:
    count: 3
    delay: 5

platform: github
server:
  domain: github.com
  protocol: https

username: "3timeslazy"
token:
  - blah-blah
```

The first run of the container

```
$ docker compose up

git-sync-1  | {"level":"info","time":"2025-01-10T17:16:03.476Z","message":"Config file not found, creating a new one..."}
git-sync-1  | {"level":"info","time":"2025-01-10T17:16:03.478Z","message":"Config loaded from: /git-sync/config.yaml"}
git-sync-1  | {"level":"fatal","time":"2025-01-10T17:16:03.478Z","message":"Error validating config: username cannot be empty when no raw git URLs are provided"}
```

`config.yaml` after the first run

```yaml
backup_dir: /root/git-backups
clone_type: bare
concurrency: 5
cron: ""
exclude_orgs: []
exclude_repos: []
include_forks: false
include_orgs: []
include_repos: []
include_wiki: true
platform: github
raw_git_urls: []
retry:
    count: 3
    delay: 5
server:
    domain: github.com
    protocol: https
token:
    - blah-blah
tokens: []
username: ""
workspace: ""
```

Run container first time, but with debug log level gives

```
$ docker compose up

git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.721Z","message":"Logger initialized"}
git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.721Z","message":"Using config file: /git-sync/config.yaml"}
git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.722Z","message":"Error in loading config file: %!(EXTRA *mapstructure.Error=1 error(s) decoding:\n\n* 'token' expected type 'string', got unconvertible type '[]interface {}', value: '[blah-blah]')"}
git-sync-1  | {"level":"info","time":"2025-01-10T17:18:18.722Z","message":"Config file not found, creating a new one..."}
git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.722Z","message":"Using default backup directory: /root/git-backups"}
git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.722Z","message":"Using config file: /git-sync/config.yaml"}
git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.724Z","message":"Using backup directory: /backups"}
git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.724Z","message":"Using config file: /git-sync/config.yaml"}
git-sync-1  | {"level":"info","time":"2025-01-10T17:18:18.724Z","message":"Config loaded from: /git-sync/config.yaml"}
git-sync-1  | {"level":"debug","time":"2025-01-10T17:18:18.724Z","message":"Validating config ⏳"}
git-sync-1  | {"level":"fatal","time":"2025-01-10T17:18:18.724Z","message":"Error validating config: username cannot be empty when no raw git URLs are provided","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/go/src/app/pkg/logger/logger.go:101\ngithub.com/AkashRajpurohit/git-sync/cmd.init.func1\n\t/go/src/app/cmd/root.go:62\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\ngithub.com/AkashRajpurohit/git-sync/cmd.Execute\n\t/go/src/app/cmd/root.go:145\nmain.main\n\t/go/src/app/main.go:6\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
```
