### ISSUE TITLE
server is required, while mentioned as optional in the documentation

### ISSUE THREAD

**Issue by 3timeslazy** [AkashRajpurohit/git-sync#86]
### Describe the Bug

The `server` option is required even if the `platform` is "github"

### Steps to reproduce

A failing config:

```yaml
backup_dir: /backups
clone_type: bare
concurrency: 5
include_forks: false
include_wiki: true
retry:
    count: 3
    delay: 5
platform: github
username: "3timeslazy"
token: "token"
```

### Relevant log output

```shell
git-sync-1  | {"level":"warn","time":"2025-01-08T22:14:39.426Z","message":"Using 'token' field is deprecated. Please use 'tokens' array instead."}
git-sync-1  | {"level":"info","time":"2025-01-08T22:14:39.426Z","message":"Config loaded from: /git-sync/config.yaml"}
git-sync-1  | {"level":"fatal","time":"2025-01-08T22:14:39.426Z","message":"Error validating config: server domain cannot be empty when no raw git URLs are provided"}
git-sync-1 exited with code 1
```

### Which version of the software are you using?

v0.15.1

### Which operating system are you using?

linux

### runtime

Docker

**Comment by AkashRajpurohit** [comment]
Seems like a regression, we can use sensible defaults if platform is specified already. Thanks for flagging this.

**Comment by AkashRajpurohit** [comment]
For now to unblock yourself on the current version, you can pass the server option like this:
```yaml
server:
  domain: github.com
  protocol: https
```
